//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PatchConfig.rc
//
#define IDS_SHOWADVOPT                  1
#define IDS_HIDEADVOPT                  2
#define IDS_NOCHOOSEN                   3
#define IDS_NODESC                      4
#define IDS_CORRUPTFILE                 5
#define IDS_CORRUPTFILE_TITLE           6
#define IDS_CORRUPTCONFIG               7
#define IDS_CORRUPTCONFIG_TITLE         8
#define IDS_WAITINGVERIFY               9
#define IDS_WAITINGLOADCFG              10
#define IDS_WAITINGENUMD3D              11
#define IDS_CONFIRMQUIT                 12
#define IDS_CONFIRMQUIT_TITLE           13
#define IDS_CANTSAVE                    14
#define IDS_CANTSAVE_TITLE              15
#define IDS_AUTORESOLUTION              16
#define IDS_AUTOSELECT                  17
#define IDS_AUTOZBUF16                  18
#define IDS_AUTOZBUF24                  19
#define IDS_ZBUF_D3DFMT_D16             20
#define IDS_ZBUF_D3DFMT_D15S1           21
#define IDS_ZBUF_D3DFMT_D24X8           22
#define IDS_ZBUF_D3DFMT_D24S8           23
#define IDS_ZBUF_D3DFMT_D24X4S4         24
#define IDS_ZBUF_D3DFMT_D32             25
#define IDS_MSAA_NONE                   26
#define IDS_MSAA_FORMAT                 27
#define IDS_AUTORESOLUTION_DESC         28
#define IDS_AUTOSELECT_DESC             29
#define IDS_MSAA_NONE_DESC              30
#define IDS_APPTITLE                    31
#define IDS_DEFAULTFONT                 32
#define IDS_DEFAULTFONT_DESC            33
#define IDS_CANTOPENGAMEFOLDER          34
#define IDS_CANTOPENGAMEFOLDER_TITLE    35
#define IDS_OPENGAMEFOLDERINPROGRESS    36
#define IDS_RESTOREDEFAULT_CONFIRM      38
#define IDS_RESTOREDEFAULT_TITLE        39
#define IDS_RESTOREDEFAULT_SUCCEED      41
#define IDS_RESTOREDEFAULT_RETRY        42
#define IDS_WAITCHECKFORUPDATES         43
#define IDS_CHECKFORUPDATES_TITLE       44
#define IDS_CHECKFORUPDATES_NEWVERSIONFOUND 45
#define IDS_CHECKFORUPDATES_NONEWVERSION 46
#define IDS_CHECKFORUPDATES_RETRY       47
#define IDS_WAITOPENWEBSITE             48
#define IDS_CANTOPENWEBSITE             49
#define IDS_CHECKFORUPDATES_ERROR       50
#define IDS_CHECKFORUPDATES_INFO        51
#define IDS_OPENCONFIGTOOLINPROGRESS    52
#define IDS_CANTOPENCONFIGTOOL          53
#define IDS_CANTOPENCONFIGTOOL_TITLE    54
#define IDS_CONFIGDESCLIST              55
#define IDS_FREETYPEFONT                56
#define IDS_FREETYPEFONT_DESC           57
#define IDS_GDIFONT_DESC                58
#define IDS_FREETYPEFONT_FILTER         59
#define IDS_RESOLUTION_DESC             60
#define IDS_OPENCONFIGTOOLWAITFINISH    61
#define IDS_HAVEBADFILE                 62
#define IDS_HAVEBADFILE_TITLE           63
#define IDS_WAITINGCHECKBADFILES        64
#define IDS_CANTDELBADFILE              65
#define IDS_CANTDELBADFILE_TITLE        66
#define IDS_NOD3D9                      67
#define IDS_NOD3D9_TITLE                68
#define IDS_WAITINGCHECKSYSTEM          69
#define IDS_BADCOMCTL32                 70
#define IDS_BADCOMCTL32_TITLE           71
#define IDS_NOMUTEX                     72
#define IDS_NOMUTEX_TITLE               73
#define IDS_MSAA_NONMASKABLE_FORMAT     74
#define IDS_RESTOREDEFAULT_FAILED       75
#define IDS_REPAIRGAMEDATA              76
#define IDS_LOADREPAIRPACK              77
#define IDS_BADREPAIRPACK               78
#define IDS_SELECTLOCALE                79
#define IDS_SELECTLOCALE_TITLE          80
#define IDS_REPAIRCORE                  81
#define IDS_REPAIRCORE_FILE             82
#define IDS_REPAIRCORE_CPK              83
#define IDS_REPAIRMUSIC                 84
#define IDS_REPAIRMUSIC_MUSIC           85
#define IDS_REPAIRMUSIC_SOUND           86
#define IDS_REPAIRMOVIE                 87
#define IDS_REPAIRMOVIE_CPK             88
#define IDS_REPAIRMISC                  89
#define IDS_REPAIRMISC_FILE             90
#define IDS_REPAIR_NEEDFIX              91
#define IDS_REPAIR_CANTFIX              92
#define IDS_REPAIR_ASKFIX               93
#define IDS_REPAIR_GOOD                 94
#define IDS_REPAIR_REPORT               95
#define IDS_REPAIR_COMMITOK             96
#define IDS_REPAIR_COMMITPART           97
#define IDS_REPAIR_COMMITERROR          98
#define IDS_REPAIR_COMMITABORT          99
#define IDS_REPAIR_COMMITREPORT         100
#define IDS_REPAIR_BADCOMMIT            101
#define IDD_PATCHCONFIG                 102
#define IDS_REPAIR_BADCOMMIT_TITLE      102
#define IDS_REPAIR_CHECKDONE            103
#define IDS_REPAIR_COMMIT               104
#define IDS_ASKCANCELREPAIR             105
#define IDR_MAINFRAME                   128
#define IDD_CHOOSEFROMLIST              129
#define IDD_PLEASEWAIT                  130
#define IDR_DEFCONFIG                   132
#define IDC_CFGTREE                     1000
#define IDC_CFGDESC                     1001
#define IDC_OPTDESC                     1006
#define IDC_RADIO1                      1008
#define IDC_RADIO2                      1009
#define IDC_RADIO3                      1010
#define IDC_CFGVAL                      1011
#define IDC_CFGTITLE                    1012
#define IDC_CHOOSEFROMLIST              1013
#define IDC_TOGGLEADVOPTS               1014
#define IDC_ENUMLIST                    1015
#define IDC_WAITMESSAGE                 1016
#define IDC_WAITMESSAGE2                1016
#define IDC_RUNFUNC                     1018
#define IDC_PROGRESS1                   1019
#define IDC_WAITPROGRESS                1019
#define IDC_BUTTON1                     1020
#define IDC_WAITMESSAGE1                1021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1022
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
